### ISSUE TITLE
Unclear how to join intro conversation

### ISSUE THREAD

**Issue by hatboysam** [DevProgress/DevProgress#2]
Apologies if this is the wrong place to leave this feedback but I can't find any other way to contact DevProgress.

I filled out a volunteer intake form and was scheduled for an 8:00am Intro Conversation today.  I added the event to my calendar.

Nobody contacted me and the only information I have is this link:
https://app.acuityscheduling.com/schedule.php?owner=12552509&id[]=d65180d47d4f645d12cbf7dc6393333f&action=appt

On that link there is no information on **how to actually join the call**.  Should I be initiating it?  Is it on Skype?  Hangouts?  I do want to get involved but I can't figure out how.

**Comment by suzannehillman** [comment]
Huh. You should have gotten an invite in the mail which included a link to an online meeting. At least, that's what I had happen. Do you know if you're receiving mail from devprogress?

**Comment by bradyk** [comment]
Just sent you an email @hatboysam. Sorry for the confusion!
